### ISSUE TITLE
Stock donut is too tight

### ISSUE THREAD

**Issue by T-Kyouko** [T-Kyouko/fossberg-500#3]

**Comment by mpewthers** [comment]
Top and bottom of the receiver taper too much and the stock overhangs. It looks like they got reduced by the same amount that the sides did, despite not being made thicker.

**Comment by T-Kyouko** [comment]
Redrew taper to only cut sides. 
Increased donut to 0.8x1.175"

**Comment by T-Kyouko** [comment]
Fixed in [ad12b78](https://github.com/T-Kyouko/fossberg-500/commit/ad12b78b0a757dd001e0bf4101c5c78bce931861)
Needs print verification.

**Comment by T-Kyouko** [comment]
Print verified. Fits nicely.
