### ISSUE TITLE
Safety is non functional

### ISSUE THREAD

**Issue by T-Kyouko** [T-Kyouko/fossberg-500#5]
Kit didnt come with all safety components so I was unable to model in the underside of the safety. Considering 3d printing a replacement based off of images I see online

**Comment by mpewthers** [comment]
On my receiver, the aluminum is .243” thick through the slot for the safety. The interior surface is parallel to the exterior for the full length of the slot, but not beyond. 

Also, the shallow channel that the thumb switch slides in is about 1/16 longer in front.

**Comment by T-Kyouko** [comment]
Set parallel dimension 0.243 and moved safety shallow notch up

**Comment by T-Kyouko** [comment]
Fixed in [ad12b78](https://github.com/T-Kyouko/fossberg-500/commit/ad12b78b0a757dd001e0bf4101c5c78bce931861)
Needs print verification.

**Comment by T-Kyouko** [comment]
@mpewthers can you model

**Comment by mpewthers** [comment]
I can try; what do you need from me? I've got very limited CADD experience, and it's all in a construction/architectural context.
