### ISSUE TITLE
Ejector is too far back

### ISSUE THREAD

**Issue by mpewthers** [T-Kyouko/fossberg-500#6]
The ejector on my Mossberg 500AG is .165" further forward than in this model. The little tab at the front of it slots into a niche in the barrel extension.

**Comment by T-Kyouko** [comment]
Is it installed right? My reference model has it pretty much where it is in this model?

**Comment by mpewthers** [comment]
Really only one way it will go in. Difference between variants of 500s, maybe?

**Comment by T-Kyouko** [comment]
Hmm the only difference between the 500A and 500AG should be wood v plastic furni

Whats your front face to hole center measurement?
![Screenshot_2023-01-05_22-17-58](https://user-images.githubusercontent.com/42362076/210923121-ce1f51d1-f6c3-470c-90d6-daa6cf11d7cc.png)

**Comment by mpewthers** [comment]
2.0625"

**Comment by T-Kyouko** [comment]
My kit also appears to be old as balls as well. My Ejector comes today, so ill have another data point.

**Comment by T-Kyouko** [comment]
Ejector was delivered, and yeah. Can confirm its too far back. I've settled on moving the mount forward 0.215" to get everything to line up. 

Opinions on making provisions for a 6-32 pan head machine screw and nut instead of using the stock screw threaded in

**Comment by mpewthers** [comment]
Good idea; I think that would be a lot more durable than using the regular screw with its limited thread engagement in plastic. 

I'm giving up on my fuzzy print... too much tolerance stacking. I'll have a new one printed in a couple of days.

**Comment by T-Kyouko** [comment]
Print verified with 4-40x3/4" pan head screw and outside nut. Sits too far up but forward to back is resolved
