### ISSUE TITLE
Ejector sit too far up

### ISSUE THREAD

**Issue by T-Kyouko** [T-Kyouko/fossberg-500#8]
Causes barrel to cock clockwise and causes binding issues on lockup. Recommend moving 50 thou down and seeing it it improves. Barrel should lock straight and true.

**Comment by T-Kyouko** [comment]
Fixed in 7b9d39dc079a9a79bf0417f3b04aca82dd96cc2d needs print verified

**Comment by T-Kyouko** [comment]
print verified

**Comment by mpewthers** [comment]
Can you cycle your bolt with the ejector installed? Mine binds on the bolt. Ejector recess on my Mossberg is .110", recess on my print of the newest iteration of the fossberg is .090"

**Comment by T-Kyouko** [comment]
Yes I'm not having any issues cycling on my print. Is your barrel installed? Without a barrel the bolt goes too far forward and slips off the rail.

**Comment by mpewthers** [comment]
Yeah, barrel is installed. I'll try to sand the print down a bit to see if that gets me the needed clearance.
